trigger:
  branches:
    include:
      - main
      - master

pool:
  vmImage: ubuntu-latest

variables:
  dockerRegistryServiceConnection: 'acr-connection'
  imageRepository: 'claimstatus'
  containerRegistry: 'introspect2bacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/ClaimStatus/Dockerfile'
  tag: '$(Build.BuildId)'
  imageName: '$(containerRegistry)/$(imageRepository):latest'  # Full image name with tag
  resourceGroup: 'introspect-2-b'  # Replace with your Azure resource group
  location: 'westeurope'  # Replace with your Azure region
stages:
- stage: Build
  displayName: 'Build and Push Image'
  jobs:
  - job: Build
    displayName: 'Build Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
       echo "Current working directory: $(pwd)"
       echo "--- Listing contents of $(Build.SourcesDirectory) (Repo Root) ---"
       ls -F $(Build.SourcesDirectory)
       echo "--- Listing contents of ClaimStatus/ directory (Expected Dockerfile location) ---"
       ls -F $(Build.SourcesDirectory)/ClaimStatus/
      displayName: 'D01: Verify File Paths'
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
        buildContext: $(System.DefaultWorkingDirectory)
    - task: Docker@2
      displayName: 'Push Image to ACR'
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: 'Deploy to Azure Container Apps'
  dependsOn: Build
  variables:
    containerRegistryName: 'introspect2bacrTest'  # Name of your Azure Container Registry
    bicepFilePath: '$(Build.SourcesDirectory)/iac/aca-deploy.bicep'  # Path to the Bicep file
  jobs:
  - job: Deploy
    displayName: 'Deploy Application'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Azure Containe Registry using Bicep'
      inputs:
            azureSubscription: 'azure-subscription'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
            # Check if the ACR resource exists
            echo "Checking if ACR resource exists: $(containerRegistry)"
            acrExists=$(az acr show --name $(containerRegistry) --query "name" --output tsv 2>/dev/null || echo "")
    
            if [ -n "$acrExists" ]; then
                echo "Azure Container Registry $(containerRegistry) already exists. Deployment will not proceed."
                exit 1
            else
                echo "Azure Container Registry $(containerRegistry) does not exist. Proceeding with deployment."
            fi
    
            # Deploy the ACR using the Bicep template
            az deployment group create \
                --resource-group $(resourceGroup) \
                --template-file $(bicepFilePath) \
                --parameters containerRegistryName=$(containerRegistryName) location=$(location)
    - task: AzureCLI@2
      displayName: 'Deploy to Azure Container Apps using Bicep'
      inputs:
        azureSubscription: 'azure-subscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Check if the ACR resource exists
          echo "Checking if ACR resource exists: $(containerRegistry)"
          acrExists=$(az acr show --name $(containerRegistry) --query "name" --output tsv 2>/dev/null || echo "")

          if [ -n "$appExists" ]; then
            echo "Azure Container App $(imageRepository) already exists. Deployment will not proceed."
            exit 1
          else
            echo "Azure Container App $(imageRepository) does not exist. Proceeding with deployment."
          fi

          # Deploy the application using the Bicep template
          az deployment group create \
            --resource-group $(resourceGroup) \
            --template-file $(bicepFilePath) \
            --parameters containerImage=$(imageName) location=$(location)